const db = [
{ name: 'HORTALIÇAS-FRUTOS',
  season: [],
  isClass: true,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Abóbora-Todas',
  season: 
   [ 'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Fraco' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Abobrinha',
  season: 
   [ 'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Forte',
     'Forte',
     'Forte' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Berinjela',
  season: 
   [ 'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Forte',
     'Forte',
     'Forte' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Chuchu',
  season: 
   [ 'Fraco',
     'Fraco',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Jilo',
  season: 
   [ 'Medio',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Fraco',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Milho Verde',
  season: 
   [ 'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Fraco',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Pepino ( Todos )',
  season: 
   [ 'Fraco',
     'Medio',
     'Forte',
     'Medio',
     'Medio',
     'Fraco',
     'Forte',
     'Fraco',
     'Medio',
     'Medio',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Pimentão',
  season: 
   [ 'Forte',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Fraco',
     'Medio',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Quiabo',
  season: 
   [ 'Medio',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Tomate',
  season: 
   [ 'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Medio',
     'Forte',
     'Forte',
     'Forte' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'Vagem',
  season: 
   [ 'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Fraco',
     'Forte',
     'Forte',
     'Forte' ],
  isClass: false,
  family: 'HORTALIÇAS-FRUTOS' },
{ name: 'HORTALIÇAS-TUBEROSAS',
  season: [],
  isClass: true,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Alho',
  season: 
   [ 'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Fraco',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Batata',
  season: 
   [ 'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Fraco',
     'Medio',
     'Forte',
     'Forte',
     'Fraco',
     'Medio',
     'Forte' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Batata-Doce',
  season: 
   [ 'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Medio',
     'Fraco' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Batata-Salsa',
  season: 
   [ 'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Fraco' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Beterraba',
  season: 
   [ 'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Forte',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Cebola',
  season: 
   [ 'Medio',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Cenoura',
  season: 
   [ 'Medio',
     'Fraco',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Medio',
     'Forte' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Inhame',
  season: 
   [ 'Fraco',
     'Medio',
     'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Fraco',
     'Fraco' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Mandioca-Aipim',
  season: 
   [ 'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Fraco',
     'Fraco' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Nabo',
  season: 
   [ 'Medio',
     'Fraco',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' },
{ name: 'Rabanete',
  season: 
   [ 'Fraco',
     'Fraco',
     'Fraco',
     'Medio',
     'Medio',
     'Medio',
     'Forte',
     'Forte',
     'Forte',
     'Medio',
     'Medio',
     'Medio' ],
  isClass: false,
  family: 'HORTALIÇAS-TUBEROSAS' }
]